### ISSUE TITLE
Example 4_GetNetworkFromQuery.py throws an error

### ISSUE THREAD

**Issue by smirnovai91** [filipinascimento/openalexnet#1]
Hi there,

I was running the Example 4 on a sample of authors and got this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_3092/1237805180.py in <module>
     29         entities = openalex.getEntities(entityType, filter=filterData)
     30 
---> 31         networks = oanet.createNetworks(entities,
     32                                         networkTypes=["coauthorship","citation"],
     33                                         simplifyNetworks=True,

~\Anaconda3\lib\site-packages\openalexnet\network.py in createNetworks(workEntities, networkTypes, simplifyNetworks, keptAttributes, ignoreAttributes, showProgress)
    212                 if(not author):
    213                     continue
--> 214                 authorID = openAlexID2Int(author["id"])
    215                 if(authorID not in authorID2Index):
    216                     authorID2Index[authorID] = len(index2AuthorID)

~\Anaconda3\lib\site-packages\openalexnet\network.py in openAlexID2Int(openAlexID)
     62         Integer corresponding to the OpenAlex ID.
     63     """
---> 64     return int(openAlexID.split("/")[-1][1:])
     65 
     66 def int2OpenAlexID(intID,entityType="works"):

AttributeError: 'NoneType' object has no attribute 'split'
```

Any ideas on how to fix this?

Thanks!

**Comment by smirnovai91** [comment]
The issue arose when I queried the OpenAlex id = A301792951

**Comment by filipinascimento** [comment]
Thanks @smirnovai91. I will investigate the issue asap. Probably Openalex is returning something that is malformed or I'm overlooking something.

Tasks for @filipinascimento 
 - [x] Replicate issue for `author:A301792951`
         OpenAlex do not have an author ID for a coauthor: `{'id': None, 'display_name': 'Jing Liu', 'orcid': None}`
 - [x] Debug and add try/raise 
 - [x] PR preparation
 - [x] Test
 - [x] Merge to master
 - [x] Update pypy package

**Comment by filipinascimento** [comment]
Please @smirnovai91, can you try again? You may need to update the package with `pip install -U openalexnet` or install it again from the github repo if you downloaded the source.

**Comment by smirnovai91** [comment]
Just tried - worked without any issues! Thanks so much for such a quick fix!:)
